In [1]:
import pandas as pd
# import numpy as np

In [2]:
database_type = "/training"

#### Reading in Training Tables

In [3]:
lab = pd.read_csv('../eICU' + database_type + '/lab.csv')
lab

         patientunitstayid  labresultoffset  creatinine  wbcx1000  lactate
0                   141168             1701      173.12       NaN      NaN
1                   141168             2026        2.95      19.8     12.2
2                   141168             1133        2.30      14.7      NaN
3                   141168              516        1.95       9.8      NaN
4                   141178             -280        0.70       7.6      NaN
5                   141179               82        0.70       NaN      NaN
6                   141179             1487        0.70       8.1      NaN
7                   141179              750        0.70       NaN      NaN
8                   141194            11658        1.75       8.9      NaN
9                   141194            10397        1.74       8.7      NaN
10                  141194             8762        1.77       6.9      NaN
11                  141194             2876        2.15       NaN      NaN
12                  141194             1630        2.26      10.9      NaN
13                  141194              762        2.28       NaN      NaN
14                  141194              312        2.51      14.1      1.3
15                  141194             2223        2.17       NaN      NaN
16                  141194             1237        2.23       NaN      NaN
17                  141194             5897        1.82       4.3      NaN
18                  141194             7303        1.84       4.6      NaN
19                  141194             4663        1.97       4.4      NaN
20                  141194             -923        2.94      11.8      NaN
21                  141194             2998        2.09       4.6      NaN
22                  141196             4987        0.83      12.7      NaN
23                  141196             3600        0.89      14.2      NaN
24                  141196              628        0.80      26.2      NaN
25                  141197             -179        0.93      29.5      NaN
26                  141203                1        0.56      12.7      3.5
27                  141203             1091        0.71      23.3      NaN
28                  141203             -473        0.39       8.5      NaN
29                  141203            -1580        0.33      10.2      NaN
...                    ...              ...         ...       ...      ...
1288978            3353237             7743        0.60       5.7      NaN
1288979            3353237             6255        0.73       NaN      NaN
1288980            3353237             3342        0.93       7.3      NaN
1288981            3353251            11058        3.98      17.6      NaN
1288982            3353251            13970        4.02       NaN      NaN
1288983            3353251            18327        2.28      18.3      NaN
1288984            3353251             8246        3.29      13.6      NaN
1288985            3353251            16867        2.78       NaN      NaN
1288986            3353251            12458        3.94      18.6      NaN
1288987            3353251             9644        3.79      15.4      NaN
1288988            3353251              765        2.65      25.9      NaN
1288989            3353251            15598        3.23       NaN      NaN
1288990            3353251             1490        2.40      20.8      NaN
1288991            3353251              995        2.60      21.5      NaN
1288992            3353251             3863        3.40      14.4      NaN
1288993            3353251             2541        3.08      26.1      NaN
1288994            3353251             1127        2.41      20.4      NaN
1288995            3353251             -217        1.81       NaN      NaN
1288996            3353251             5459        3.29      11.9      NaN
1288997            3353251             6868        3.35      13.0      NaN
1288998            3353251             1849        2.46      25.9      NaN
1288999            3353251              409        2.43       NaN      NaN
1289000            3353254             2610        1.92       9.8      NaN
1289001            3353254             1844        2.22       NaN      NaN
1289002            3353254             1218        2.21      15.3      NaN
1289003            3353254             5558        1.67      11.7      NaN
1289004            3353254             4144        1.61       NaN      NaN
1289005            3353254             -256        2.38      13.5      NaN
1289006            3353263               -7        1.06       6.5      NaN
1289007            3353263               -7        1.06       6.4      NaN

[1289008 rows x 5 columns]

In [4]:
vitalperiodic = pd.read_csv('../eICU' + database_type + '/vitalPeriodic.csv')
vitalperiodic

,patientunitstayid,observationoffset,temperature,heartrate,respiration,systemicsystolic
0,141168,2059,NaN,92.0,NaN,NaN
1,141168,1289,NaN,118.0,NaN,NaN
2,141168,1794,NaN,78.0,NaN,NaN
3,141168,1374,NaN,118.0,NaN,NaN
4,141168,2039,NaN,92.0,NaN,NaN
5,141168,1569,NaN,80.0,NaN,NaN
6,141168,2119,NaN,104.0,NaN,NaN
7,141168,419,NaN,132.0,NaN,NaN
8,141168,754,NaN,128.0,NaN,NaN
9,141168,1594,NaN,80.0,NaN,NaN
10,141168,1389,NaN,78.0,NaN,NaN
11,141168,294,NaN,132.0,NaN,NaN
12,141168,644,NaN,130.0,NaN,NaN
13,141168,1249,NaN,120.0,NaN,NaN
14,141168,1749,NaN,78.0,NaN,NaN
15,141168,119,NaN,140.0,NaN,NaN
16,141168,1974,NaN,72.0,NaN,NaN
17,141168,1084,NaN,120.0,NaN,NaN
18,141168,689,NaN,130.0,NaN,NaN
19,141168,1809,NaN,78.0,NaN,NaN
20,141168,2254,NaN,100.0,NaN,100.0
21,141168,1649,NaN,76.0,NaN,NaN
22,141168,1439,NaN,80.0,NaN,NaN
23,141168,299,NaN,132.0,NaN,NaN
24,141168,679,NaN,130.0,NaN,NaN
25,141168,1204,NaN,120.0,NaN,NaN
26,141168,1789,NaN,78.0,NaN,NaN
27,141168,1549,NaN,80.0,NaN,NaN
28,141168,1984,NaN,74.0,NaN,NaN
29,141168,944,NaN,124.0,NaN,NaN
...,...,...,...,...,...,...
146671595,3353263,144,NaN,79.0,13.0,NaN
146671596,3353263,74,NaN,95.0,29.0,NaN
146671597,3353263,174,NaN,79.0,12.0,NaN
146671598,3353263,109,NaN,81.0,14.0,NaN
146671599,3353263,149,NaN,79.0,12.0,NaN
146671600,3353263,44,NaN,93.0,36.0,NaN
146671601,3353263,524,NaN,79.0,24.0,NaN
146671602,3353263,514,NaN,91.0,34.0,NaN
146671603,3353263,499,NaN,81.0,24.0,NaN
146671604,3353263,509,NaN,90.0,42.0,NaN
146671605,3353263,594,NaN,77.0,19.0,NaN
146671606,3353263,529,NaN,80.0,19.0,NaN
146671607,3353263,519,NaN,84.0,36.0,NaN
146671608,3353263,579,NaN,86.0,25.0,NaN
146671609,3353263,539,NaN,82.0,30.0,NaN
146671610,3353263,489,NaN,82.0,30.0,NaN
146671611,3353263,584,NaN,82.0,20.0,NaN
146671612,3353263,554,NaN,69.0,17.0,NaN
146671613,3353263,589,NaN,78.0,14.0,NaN
146671614,3353263,574,NaN,83.0,22.0,NaN
146671615,3353263,484,NaN,86.0,45.0,NaN
146671616,3353263,494,NaN,81.0,29.0,NaN
146671617,3353263,569,NaN,80.0,25.0,NaN
146671618,3353263,564,NaN,78.0,18.0,NaN
146671619,3353263,559,NaN,74.0,16.0,NaN
146671620,3353263,504,NaN,87.0,36.0,NaN
146671621,3353263,534,NaN,81.0,21.0,NaN
146671622,3353263,549,NaN,78.0,14.0,NaN
146671623,3353263,544,NaN,85.0,25.0,NaN
146671624,3353263,599,NaN,75.0,13.0,NaN

In [5]:
# The original dataframes were deleted to free up resources.  
merge = pd.merge(vitalperiodic, lab,  how='outer', left_on=['patientunitstayid','observationoffset'], right_on = ['patientunitstayid','labresultoffset'])
del lab, vitalperiodic
merge

,patientunitstayid,observationoffset,temperature,heartrate,respiration,systemicsystolic,labresultoffset,creatinine,wbcx1000,lactate
0,141168,2059.0,NaN,92.0,NaN,NaN,NaN,NaN,NaN,NaN
1,141168,1289.0,NaN,118.0,NaN,NaN,NaN,NaN,NaN,NaN
2,141168,1794.0,NaN,78.0,NaN,NaN,NaN,NaN,NaN,NaN
3,141168,1374.0,NaN,118.0,NaN,NaN,NaN,NaN,NaN,NaN
4,141168,2039.0,NaN,92.0,NaN,NaN,NaN,NaN,NaN,NaN
5,141168,1569.0,NaN,80.0,NaN,NaN,NaN,NaN,NaN,NaN
6,141168,2119.0,NaN,104.0,NaN,NaN,NaN,NaN,NaN,NaN
7,141168,419.0,NaN,132.0,NaN,NaN,NaN,NaN,NaN,NaN
8,141168,754.0,NaN,128.0,NaN,NaN,NaN,NaN,NaN,NaN
9,141168,1594.0,NaN,80.0,NaN,NaN,NaN,NaN,NaN,NaN
10,141168,1389.0,NaN,78.0,NaN,NaN,NaN,NaN,NaN,NaN
11,141168,294.0,NaN,132.0,NaN,NaN,NaN,NaN,NaN,NaN
12,141168,644.0,NaN,130.0,NaN,NaN,NaN,NaN,NaN,NaN
13,141168,1249.0,NaN,120.0,NaN,NaN,NaN,NaN,NaN,NaN
14,141168,1749.0,NaN,78.0,NaN,NaN,NaN,NaN,NaN,NaN
15,141168,119.0,NaN,140.0,NaN,NaN,NaN,NaN,NaN,NaN
16,141168,1974.0,NaN,72.0,NaN,NaN,NaN,NaN,NaN,NaN
17,141168,1084.0,NaN,120.0,NaN,NaN,NaN,NaN,NaN,NaN
18,141168,689.0,NaN,130.0,NaN,NaN,NaN,NaN,NaN,NaN
19,141168,1809.0,NaN,78.0,NaN,NaN,NaN,NaN,NaN,NaN
20,141168,2254.0,NaN,100.0,NaN,100.0,NaN,NaN,NaN,NaN
21,141168,1649.0,NaN,76.0,NaN,NaN,NaN,NaN,NaN,NaN
22,141168,1439.0,NaN,80.0,NaN,NaN,NaN,NaN,NaN,NaN
23,141168,299.0,NaN,132.0,NaN,NaN,NaN,NaN,NaN,NaN
24,141168,679.0,NaN,130.0,NaN,NaN,NaN,NaN,NaN,NaN
25,141168,1204.0,NaN,120.0,NaN,NaN,NaN,NaN,NaN,NaN
26,141168,1789.0,NaN,78.0,NaN,NaN,NaN,NaN,NaN,NaN
27,141168,1549.0,NaN,80.0,NaN,NaN,NaN,NaN,NaN,NaN
28,141168,1984.0,NaN,74.0,NaN,NaN,NaN,NaN,NaN,NaN
29,141168,944.0,NaN,124.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
147829658,3353235,NaN,NaN,NaN,NaN,NaN,-310.0,1.04,5.4,NaN
147829659,3353235,NaN,NaN,NaN,NaN,NaN,1738.0,1.19,NaN,NaN
147829660,3353237,NaN,NaN,NaN,NaN,NaN,4789.0,0.78,NaN,NaN
147829661,3353237,NaN,NaN,NaN,NaN,NaN,1959.0,0.88,8.6,NaN
147829662,3353237,NaN,NaN,NaN,NaN,NaN,7743.0,0.60,5.7,NaN
147829663,3353237,NaN,NaN,NaN,NaN,NaN,6255.0,0.73,NaN,NaN
147829664,3353237,NaN,NaN,NaN,NaN,NaN,3342.0,0.93,7.3,NaN
147829665,3353251,NaN,NaN,NaN,NaN,NaN,11058.0,3.98,17.6,NaN
147829666,3353251,NaN,NaN,NaN,NaN,NaN,13970.0,4.02,NaN,NaN
147829667,3353251,NaN,NaN,NaN,NaN,NaN,18327.0,2.28,18.3,NaN
147829668,3353251,NaN,NaN,NaN,NaN,NaN,8246.0,3.29,13.6,NaN
147829669,3353251,NaN,NaN,NaN,NaN,NaN,16867.0,2.78,NaN,NaN
147829670,3353251,NaN,NaN,NaN,NaN,NaN,12458.0,3.94,18.6,NaN
147829671,3353251,NaN,NaN,NaN,NaN,NaN,765.0,2.65,25.9,NaN
147829672,3353251,NaN,NaN,NaN,NaN,NaN,15598.0,3.23,NaN,NaN
147829673,3353251,NaN,NaN,NaN,NaN,NaN,1490.0,2.40,20.8,NaN
147829674,3353251,NaN,NaN,NaN,NaN,NaN,995.0,2.60,21.5,NaN
147829675,3353251,NaN,NaN,NaN,NaN,NaN,3863.0,3.40,14.4,NaN
147829676,3353251,NaN,NaN,NaN,NaN,NaN,2541.0,3.08,26.1,NaN
147829677,3353251,NaN,NaN,NaN,NaN,NaN,1127.0,2.41,20.4,NaN
147829678,3353251,NaN,NaN,NaN,NaN,NaN,-217.0,1.81,NaN,NaN
147829679,3353251,NaN,NaN,NaN,NaN,NaN,6868.0,3.35,13.0,NaN
147829680,3353254,NaN,NaN,NaN,NaN,NaN,2610.0,1.92,9.8,NaN
147829681,3353254,NaN,NaN,NaN,NaN,NaN,1844.0,2.22,NaN,NaN
147829682,3353254,NaN,NaN,NaN,NaN,NaN,1218.0,2.21,15.3,NaN
147829683,3353254,NaN,NaN,NaN,NaN,NaN,5558.0,1.67,11.7,NaN
147829684,3353254,NaN,NaN,NaN,NaN,NaN,4144.0,1.61,NaN,NaN
147829685,3353254,NaN,NaN,NaN,NaN,NaN,-256.0,2.38,13.5,NaN
147829686,3353263,NaN,NaN,NaN,NaN,NaN,-7.0,1.06,6.5,NaN
147829687,3353263,NaN,NaN,NaN,NaN,NaN,-7.0,1.06,6.4,NaN

In [6]:
intakeOutputUrine = pd.read_csv('../eICU' + database_type + '/intakeOutputUrine.csv')
intakeOutputUrine

         patientunitstayid  intakeoutputoffset  urineoutputbyweight
0                   141179                1420             3.968254
1                   141179                 933             2.834467
2                   141179                1703             5.668934
3                   141179                 678             3.968254
4                   141194               12201             1.353180
5                   141194               12042             1.353180
6                   141194                4620             7.104195
7                   141194               11955             4.059540
8                   141194               11779             9.472260
9                   141196                3026             0.513611
10                  141196                5008             0.770416
11                  141196                2485             0.642013
12                  141196                 300             1.027221
13                  141196                2796             0.770416
14                  141196                3161             0.770416
15                  141196                 840             2.311248
16                  141196                3505             1.027221
17                  141196                1826             0.770416
18                  141196                4492             1.027221
19                  141196                3759             0.770416
20                  141196                4660             0.642013
21                  141196                5140             0.770416
22                  141196                5199             0.513611
23                  141196                3973             0.770416
24                  141227               -1893             2.433090
25                  141227               -1663             2.433090
26                  141227               -1773             2.433090
27                  141227               -1351             2.433090
28                  141229                3430             4.454343
29                  141233               17012             0.810373
...                    ...                 ...                  ...
3329720            3353251               14503             1.470588
3329721            3353251               14083             1.323529
3329722            3353251                8083             1.078431
3329723            3353251               11143             1.960784
3329724            3353251               12103             2.941176
3329725            3353251                 883             1.470588
3329726            3353251                 763             1.470588
3329727            3353251               13543             1.078431
3329728            3353251               12163             0.735294
3329729            3353251                4363             3.431373
3329730            3353251                3223             0.343137
3329731            3353251               12223             0.735294
3329732            3353254                2386             4.767580
3329733            3353254                6106             7.163290
3329734            3353254                1306             4.767580
3329735            3353254                2401            10.131108
3329736            3353254                5491             2.383790
3329737            3353254                 286             2.383790
3329738            3353254                5196             2.979738
3329739            3353254                5291             3.575685
3329740            3353254                2101            10.131108
3329741            3353254                 766             4.767580
3329742            3353254                 406             5.363528
3329743            3353254                3516             2.979738
3329744            3353254                5926             7.151371
3329745            3353254                4169            19.070322
3329746            3353254                5326             4.767580
3329747            3353254                2626            10.131108
3329748            3353254                3101            15.494636
3329749            3353254                1414             0.357569

[3329750 rows x 3 columns]

In [7]:
merge1 = pd.merge(merge, intakeOutputUrine,  how='outer', left_on=['patientunitstayid','observationoffset'], right_on = ['patientunitstayid','intakeoutputoffset'])
del merge, intakeOutputUrine
merge1

,patientunitstayid,observationoffset,temperature,heartrate,respiration,systemicsystolic,labresultoffset,creatinine,wbcx1000,lactate,intakeoutputoffset,urineoutputbyweight
0,141168,2059,NaN,92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,141168,1289,NaN,118.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,141168,1794,NaN,78.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,141168,1374,NaN,118.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,141168,2039,NaN,92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,141168,1569,NaN,80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,141168,2119,NaN,104.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,141168,419,NaN,132.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,141168,754,NaN,128.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,141168,1594,NaN,80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,141168,1389,NaN,78.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,141168,294,NaN,132.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,141168,644,NaN,130.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,141168,1249,NaN,120.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,141168,1749,NaN,78.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,141168,119,NaN,140.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,141168,1974,NaN,72.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,141168,1084,NaN,120.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,141168,689,NaN,130.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,141168,1809,NaN,78.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,141168,2254,NaN,100.0,NaN,100.0,NaN,NaN,NaN,NaN,NaN,NaN
21,141168,1649,NaN,76.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,141168,1439,NaN,80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,141168,299,NaN,132.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,141168,679,NaN,130.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,141168,1204,NaN,120.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,141168,1789,NaN,78.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,141168,1549,NaN,80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,141168,1984,NaN,74.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,141168,944,NaN,124.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
150678318,3353251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14503.0,1.470588
150678319,3353251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14083.0,1.323529
150678320,3353251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8083.0,1.078431
150678321,3353251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11143.0,1.960784
150678322,3353251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12103.0,2.941176
150678323,3353251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,883.0,1.470588
150678324,3353251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,763.0,1.470588
150678325,3353251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13543.0,1.078431
150678326,3353251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12163.0,0.735294
150678327,3353251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4363.0,3.431373
150678328,3353251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3223.0,0.343137
150678329,3353251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12223.0,0.735294
150678330,3353254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2386.0,4.767580
150678331,3353254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6106.0,7.163290
150678332,3353254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1306.0,4.767580
150678333,3353254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2401.0,10.131108
150678334,3353254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5491.0,2.383790
150678335,3353254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,286.0,2.383790
150678336,3353254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5196.0,2.979738
150678337,3353254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5291.0,3.575685
150678338,3353254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2101.0,10.131108
150678339,3353254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,766.0,4.767580
150678340,3353254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,406.0,5.363528
150678341,3353254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3516.0,2.979738
150678342,3353254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5926.0,7.151371
150678343,3353254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4169.0,19.070322
150678344,3353254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5326.0,4.767580
150678345,3353254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2626.0,10.131108
150678346,3353254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3101.0,15.494636
150678347,3353254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1414.0,0.357569

In [8]:
path = "../eICU/training/"
merge1.to_csv(path + "merge1.csv", sep=',', index=False, encoding='utf-8')