In [2]:
import pandas as pd

In [3]:
database_type = "/training"

In [4]:
merge2 = pd.read_csv('../eICU' + database_type + '/merge2.csv')
merge2

,patientunitstayid,observationoffset,temperature,heartrate,respiration,systemicsystolic,creatinine,wbcx1000,lactate,urineoutputbyweight
0,141168,2059.0,NaN,92.0,NaN,NaN,NaN,NaN,NaN,NaN
1,141168,1289.0,NaN,118.0,NaN,NaN,NaN,NaN,NaN,NaN
2,141168,1794.0,NaN,78.0,NaN,NaN,NaN,NaN,NaN,NaN
3,141168,1374.0,NaN,118.0,NaN,NaN,NaN,NaN,NaN,NaN
4,141168,2039.0,NaN,92.0,NaN,NaN,NaN,NaN,NaN,NaN
5,141168,1569.0,NaN,80.0,NaN,NaN,NaN,NaN,NaN,NaN
6,141168,2119.0,NaN,104.0,NaN,NaN,NaN,NaN,NaN,NaN
7,141168,419.0,NaN,132.0,NaN,NaN,NaN,NaN,NaN,NaN
8,141168,754.0,NaN,128.0,NaN,NaN,NaN,NaN,NaN,NaN
9,141168,1594.0,NaN,80.0,NaN,NaN,NaN,NaN,NaN,NaN
10,141168,1389.0,NaN,78.0,NaN,NaN,NaN,NaN,NaN,NaN
11,141168,294.0,NaN,132.0,NaN,NaN,NaN,NaN,NaN,NaN
12,141168,644.0,NaN,130.0,NaN,NaN,NaN,NaN,NaN,NaN
13,141168,1249.0,NaN,120.0,NaN,NaN,NaN,NaN,NaN,NaN
14,141168,1749.0,NaN,78.0,NaN,NaN,NaN,NaN,NaN,NaN
15,141168,119.0,NaN,140.0,NaN,NaN,NaN,NaN,NaN,NaN
16,141168,1974.0,NaN,72.0,NaN,NaN,NaN,NaN,NaN,NaN
17,141168,1084.0,NaN,120.0,NaN,NaN,NaN,NaN,NaN,NaN
18,141168,689.0,NaN,130.0,NaN,NaN,NaN,NaN,NaN,NaN
19,141168,1809.0,NaN,78.0,NaN,NaN,NaN,NaN,NaN,NaN
20,141168,2254.0,NaN,100.0,NaN,100.0,NaN,NaN,NaN,NaN
21,141168,1649.0,NaN,76.0,NaN,NaN,NaN,NaN,NaN,NaN
22,141168,1439.0,NaN,80.0,NaN,NaN,NaN,NaN,NaN,NaN
23,141168,299.0,NaN,132.0,NaN,NaN,NaN,NaN,NaN,NaN
24,141168,679.0,NaN,130.0,NaN,NaN,NaN,NaN,NaN,NaN
25,141168,1204.0,NaN,120.0,NaN,NaN,NaN,NaN,NaN,NaN
26,141168,1789.0,NaN,78.0,NaN,NaN,NaN,NaN,NaN,NaN
27,141168,1549.0,NaN,80.0,NaN,NaN,NaN,NaN,NaN,NaN
28,141168,1984.0,NaN,74.0,NaN,NaN,NaN,NaN,NaN,NaN
29,141168,944.0,NaN,124.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
150678318,3353251,14503.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.470588
150678319,3353251,14083.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.323529
150678320,3353251,8083.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.078431
150678321,3353251,11143.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.960784
150678322,3353251,12103.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.941176
150678323,3353251,883.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.470588
150678324,3353251,763.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.470588
150678325,3353251,13543.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.078431
150678326,3353251,12163.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.735294
150678327,3353251,4363.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.431373
150678328,3353251,3223.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.343137
150678329,3353251,12223.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.735294
150678330,3353254,2386.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.767580
150678331,3353254,6106.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.163290
150678332,3353254,1306.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.767580
150678333,3353254,2401.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.131108
150678334,3353254,5491.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.383790
150678335,3353254,286.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.383790
150678336,3353254,5196.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.979738
150678337,3353254,5291.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.575685
150678338,3353254,2101.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.131108
150678339,3353254,766.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.767580
150678340,3353254,406.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.363528
150678341,3353254,3516.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.979738
150678342,3353254,5926.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.151371
150678343,3353254,4169.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.070322
150678344,3353254,5326.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.767580
150678345,3353254,2626.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.131108
150678346,3353254,3101.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.494636
150678347,3353254,1414.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.357569

In [5]:
diagnosis = pd.read_csv('../eICU' + database_type + '/diagnosis.csv')
diagnosis = diagnosis.astype({'diagnosis': int})
diagnosis

        patientunitstayid  diagnosisoffset  diagnosis
0                  141168               72          0
1                  141168              118          0
2                  141203             1141          0
3                  141203               74          0
4                  141227               18          1
5                  141229               15          0
6                  141229                9          0
7                  141266               96          0
8                  141284             1180          0
9                  141284               42          0
10                 141288              899          0
11                 141288               19          0
12                 141288              575          0
13                 141288              575          1
14                 141288              415          0
15                 141288               19          1
16                 141288              415          1
17                 141288              899          1
18                 141289               13          0
19                 141289               13          1
20                 141296               34          0
21                 141297               25          0
22                 141297               25          1
23                 141304               23          0
24                 141304              260          0
25                 141304               23          1
26                 141304              260          1
27                 141313              157          0
28                 141314               28          0
29                 141314               91          0
...                   ...              ...        ...
580405            3353226             3885          0
580406            3353226             5484          0
580407            3353226             1904          0
580408            3353226             9779          0
580409            3353226            10522          0
580410            3353226             8942          0
580411            3353235               26          0
580412            3353237              162          0
580413            3353251              108          0
580414            3353251              291          0
580415            3353251             2653          1
580416            3353251              186          0
580417            3353251            12374          0
580418            3353251             3055          1
580419            3353251             1201          0
580420            3353251             3055          0
580421            3353251            12374          1
580422            3353251            11304          0
580423            3353251             5521          0
580424            3353251             6303          0
580425            3353251             4080          0
580426            3353251             9169          0
580427            3353251             2653          0
580428            3353251             9169          1
580429            3353251            11304          1
580430            3353251             6303          1
580431            3353251             5521          1
580432            3353251             4080          1
580433            3353254               41          0
580434            3353263              100          0

[580435 rows x 3 columns]

In [6]:
finalMerge = pd.merge(merge2, diagnosis,  how='outer', left_on=['patientunitstayid','observationoffset'], right_on = ['patientunitstayid', 'diagnosisoffset'])
del merge2, diagnosis

In [7]:
path = "../eICU/training/"
finalMerge.to_csv(path + "merge3.csv", sep=',', index=False, encoding='utf-8')