In [1]:
import pandas as pd

In [2]:
database_type = "/training"

In [3]:
cleanedData = pd.read_csv('../eICU' + database_type + '/cleanedData.csv')
cleanedData

,patientunitstayid,observationoffset,temperature,heartrate,respiration,systemicsystolic,creatinine,wbcx1000,lactate,urineoutputbyweight,diagnosis
0,141227,-1893.0,38.308853,112.0,49.0,158.000000,1.40,48.20,4.300000,2.433090,0.0
1,141227,-1773.0,38.308853,112.0,49.0,158.000000,1.40,48.20,4.300000,2.433090,0.0
2,141227,-1663.0,38.308853,112.0,49.0,158.000000,1.40,48.20,4.300000,2.433090,0.0
3,141227,-1566.0,38.308853,112.0,49.0,158.000000,1.40,48.20,4.300000,2.433090,0.0
4,141227,-1351.0,38.308853,112.0,49.0,158.000000,1.40,47.95,4.300000,2.433090,0.0
...,...,...,...,...,...,...,...,...,...,...,...
38721752,3353254,5326.0,38.308853,82.0,12.0,118.646024,1.65,11.32,2.348331,4.767580,0.0
38721753,3353254,5491.0,38.308853,82.0,12.0,118.646024,1.66,11.51,2.348331,2.383790,0.0
38721754,3353254,5558.0,38.308853,82.0,12.0,118.646024,1.67,11.70,2.348331,4.767580,0.0
38721755,3353254,5926.0,38.308853,82.0,12.0,118.646024,1.67,11.70,2.348331,7.151371,0.0
38721756,3353254,6106.0,38.308853,82.0,12.0,118.646024,1.67,11.70,2.348331,7.163290,0.0

In [4]:
cleanedData = cleanedData.astype({'diagnosis': int})
cleanedData

,patientunitstayid,observationoffset,temperature,heartrate,respiration,systemicsystolic,creatinine,wbcx1000,lactate,urineoutputbyweight,diagnosis
0,141227,-1893.0,38.308853,112.0,49.0,158.000000,1.40,48.20,4.300000,2.433090,0
1,141227,-1773.0,38.308853,112.0,49.0,158.000000,1.40,48.20,4.300000,2.433090,0
2,141227,-1663.0,38.308853,112.0,49.0,158.000000,1.40,48.20,4.300000,2.433090,0
3,141227,-1566.0,38.308853,112.0,49.0,158.000000,1.40,48.20,4.300000,2.433090,0
4,141227,-1351.0,38.308853,112.0,49.0,158.000000,1.40,47.95,4.300000,2.433090,0
...,...,...,...,...,...,...,...,...,...,...,...
38721752,3353254,5326.0,38.308853,82.0,12.0,118.646024,1.65,11.32,2.348331,4.767580,0
38721753,3353254,5491.0,38.308853,82.0,12.0,118.646024,1.66,11.51,2.348331,2.383790,0
38721754,3353254,5558.0,38.308853,82.0,12.0,118.646024,1.67,11.70,2.348331,4.767580,0
38721755,3353254,5926.0,38.308853,82.0,12.0,118.646024,1.67,11.70,2.348331,7.151371,0
38721756,3353254,6106.0,38.308853,82.0,12.0,118.646024,1.67,11.70,2.348331,7.163290,0

In [5]:
idList = sorted(set(list(cleanedData['patientunitstayid'])))

In [46]:
cols = ['patientid', 'temperature_min', 'temperature_max', 'temperature_mean', 'temperature_std', 'temperature_kurtosis', 'temperature_skew', 
        'heartrate_min', 'heartrate_max', 'heartrate_mean', 'heartrate_std', 'heartrate_kurtosis', 'heartrate_skew', 'respiration_min', 
        'respiration_max', 'respiration_mean', 'respiration_std', 'respiration_kurtosis', 'respiration_skew', 'systemicsystolic_min', 
        'systemicsystolic_max', 'systemicsystolic_mean', 'systemicsystolic_std', 'systemicsystolic_kurtosis', 'systemicsystolic_skew', 
        'wbcx1000_min', 'wbcx1000_max', 'wbcx1000_mean', 'wbcx1000_std', 'wbcx1000_kurtosis', 'wbcx1000_skew', 'lactate_min', 'lactate_max', 
        'lactate_mean', 'lactate_std', 'lactate_kurtosis', 'lactate_skew', 'creatinine_min', 'creatinine_max', 'creatinine_mean', 'creatinine_std', 
        'creatinine_kurtosis', 'creatinine_skew', 'urineoutputbyweight_min', 'urineoutputbyweight_max', 'urineoutputbyweight_mean', 
        'urineoutputbyweight_std', 'urineoutputbyweight_kurtosis', 'urineoutputbyweight_skew', 'diagnosis']
# cleanedData[cols].isna().sum().sum()

In [49]:
def append_features(features, instance, diagnosis):
    features = features.append({
                'patientid': id*10 + sepsisCount,
                'temperature_min' : round(instance.temperature.min(), 4),
                'temperature_max' : round(instance.temperature.max(), 4),
                'temperature_mean' : round(instance.temperature.mean(), 4),
                'temperature_std' : round(instance.temperature.std(), 4),
                'temperature_kurtosis' : round(instance.temperature.kurtosis(), 4),
                'temperature_skew' : round(instance.temperature.skew(), 4),
                
                'heartrate_min' : round(instance.heartrate.min(), 4),
                'heartrate_max' : round(instance.heartrate.max(), 4),
                'heartrate_mean' : round(instance.heartrate.mean(), 4),
                'heartrate_std' : round(instance.heartrate.std(), 4),
                'heartrate_kurtosis' : round(instance.heartrate.kurtosis(), 4),
                'heartrate_skew' : round(instance.heartrate.skew(), 4),    

                'respiration_min' : round(instance.respiration.min(), 4),
                'respiration_max' : round(instance.respiration.max(), 4),
                'respiration_mean' : round(instance.respiration.mean(), 4),
                'respiration_std' : round(instance.respiration.std(), 4),
                'respiration_kurtosis' : round(instance.respiration.kurtosis(), 4),
                'respiration_skew' : round(instance.respiration.skew(), 4),    

                'systemicsystolic_min' : round(instance.systemicsystolic.min(), 4),
                'systemicsystolic_max' : round(instance.systemicsystolic.max(), 4),
                'systemicsystolic_mean' : round(instance.systemicsystolic.mean(), 4),
                'systemicsystolic_std' : round(instance.systemicsystolic.std(), 4),
                'systemicsystolic_kurtosis' : round(instance.systemicsystolic.kurtosis(), 4),
                'systemicsystolic_skew' : round(instance.systemicsystolic.skew(), 4),
                
                'wbcx1000_min' : round(instance.wbcx1000.min(), 4),
                'wbcx1000_max' : round(instance.wbcx1000.max(), 4),
                'wbcx1000_mean' : round(instance.wbcx1000.mean(), 4),
                'wbcx1000_std' : round(instance.wbcx1000.std(), 4),
                'wbcx1000_kurtosis' : round(instance.wbcx1000.kurtosis(), 4),
                'wbcx1000_skew' : round(instance.wbcx1000.skew(), 4),    

                'lactate_min' : round(instance.lactate.min(), 4),
                'lactate_max' : round(instance.lactate.max(), 4),
                'lactate_mean' : round(instance.lactate.mean(), 4),
                'lactate_std' : round(instance.lactate.std(), 4),
                'lactate_kurtosis' : round(instance.lactate.kurtosis(), 4),
                'lactate_skew' : round(instance.lactate.skew(), 4),    

                'creatinine_min' : round(instance.creatinine.min(), 4),
                'creatinine_max' : round(instance.creatinine.max(), 4),
                'creatinine_mean' : round(instance.creatinine.mean(), 4),
                'creatinine_std' : round(instance.creatinine.std(), 4),
                'creatinine_kurtosis' : round(instance.creatinine.kurtosis(), 4),
                'creatinine_skew' : round(instance.creatinine.skew(), 4),

                'urineoutputbyweight_min' : round(instance.urineoutputbyweight.min(), 4),
                'urineoutputbyweight_max' : round(instance.urineoutputbyweight.max(), 4),
                'urineoutputbyweight_mean' : round(instance.urineoutputbyweight.mean(), 4),
                'urineoutputbyweight_std' : round(instance.urineoutputbyweight.std(), 4),
                'urineoutputbyweight_kurtosis' : round(instance.urineoutputbyweight.kurtosis(), 4),
                'urineoutputbyweight_skew' : round(instance.urineoutputbyweight.skew(), 4),
                'diagnosis': diagnosis
            }, ignore_index=True)
    
    return features

In [53]:
features = pd.DataFrame(columns=cols)
x = 0
for id in idList:
    df = cleanedData[cleanedData['patientunitstayid'] == id]
    lastPos = len(df.index)-1
    sepsisCount = 0
    
    if x%5000 ==0:
        print(x)
    x+=1
    
    while lastPos > 0:
        if df.iloc[lastPos]['diagnosis'] == 1:
            sepsisCount+=1
            sepsisTime = df.iloc[lastPos]['observationoffset']
            
            instance = df[df['observationoffset'] <= sepsisTime]
            features = append_features(features, instance, 1)
            
        lastPos-=1
        
    if sepsisCount == 0:
        features = append_features(features, df, 0)

features

0
5000
10000
15000
20000
25000
30000
35000

,patientid,temperature_min,temperature_max,temperature_mean,temperature_std,temperature_kurtosis,temperature_skew,heartrate_min,heartrate_max,heartrate_mean,...,creatinine_std,creatinine_kurtosis,creatinine_skew,urineoutputbyweight_min,urineoutputbyweight_max,urineoutputbyweight_mean,urineoutputbyweight_std,urineoutputbyweight_kurtosis,urineoutputbyweight_skew,diagnosis
0,1412271.0,37.6965,38.3089,38.2532,0.1846,11.0000,-3.3166,103.0000,112.0,110.2727,...,0.0528,-2.4436,0.2131,2.4331,2.4331,2.4331,0.0000,0.0000,0.0000,1.0
1,1412881.0,37.6965,38.3089,38.2958,0.0886,43.1937,-6.6884,81.0000,105.0,93.7926,...,0.0707,-1.2662,0.0730,6.0060,6.0060,6.0060,0.0000,0.0000,0.0000,1.0
2,1412882.0,37.6965,38.3089,38.2937,0.0956,36.9158,-6.1892,86.0000,105.0,98.7603,...,0.0468,-1.2000,0.0000,6.0060,6.0060,6.0060,0.0000,0.0000,0.0000,1.0
3,1412883.0,37.6965,38.3089,38.2948,0.0923,40.9051,-6.4780,99.0000,105.0,101.5632,...,0.0337,-1.2000,0.0000,6.0060,6.0060,6.0060,0.0000,0.0000,0.0000,1.0
4,1412884.0,37.6965,38.3089,38.2068,0.2500,6.0000,-2.4495,100.3333,102.0,101.1667,...,0.0025,-1.2000,0.0000,6.0060,6.0060,6.0060,0.0000,0.0000,0.0000,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94613,33532515.0,32.2000,37.7000,35.9189,2.0949,-1.3428,-0.6828,51.0000,105.0,74.1516,...,0.4346,-1.0929,-0.5296,0.0980,5.6373,1.3164,1.0422,0.9901,1.1126,1.0
94614,33532516.0,32.2000,37.7000,35.3112,2.1057,-1.7574,-0.2178,51.0000,104.0,69.9972,...,0.4218,-1.1573,-0.0645,0.0980,5.6373,1.0889,0.9895,3.4195,1.6831,1.0
94615,33532517.0,32.2000,37.4000,34.5467,1.8862,-1.7703,0.2656,51.0000,104.0,67.5541,...,0.3316,-0.4349,0.1481,0.0980,5.6373,0.9832,1.0570,3.9619,1.9491,1.0
94616,33532518.0,32.2000,36.8000,34.1643,1.7398,-1.4068,0.6213,60.0000,104.0,67.8090,...,0.2710,0.4651,0.0064,0.0980,5.6373,1.0385,1.1231,2.9569,1.7434,1.0
94617,33532540.0,38.3089,38.3089,38.3089,0.0000,0.0000,0.0000,72.0000,83.0,77.3532,...,0.2039,3.1968,-2.1039,0.3576,19.0703,3.7475,2.6719,13.1009,3.2470,0.0

In [54]:
features.diagnosis.value_counts()

1.0    77916
0.0    16702
Name: diagnosis, dtype: int64

In [55]:
path = "../eICU/training/"
features.to_csv(path + "finalFeatures.csv", sep=',', index=False, encoding='utf-8')